### ISSUE TITLE
mono<=4.2

### ISSUE THREAD

**Issue by forostm** [KaOS-Community-Packages/emby-server#2]
This dependency can not be satisfied in KaOS 
KaOS provides only  mono 4.4

**Comment by Astate** [comment]
Ok.
In this case what i can do?
For this time Emby-server really need 4.2.0. 

Need to close temporary this git?

**Comment by forostm** [comment]
I think this package should be **removed temporarily** from kcp until the incompatibility is resolved (with mono 4.4).

**Comment by Astate** [comment]
The dev dont want to modify app because mono are in PREVIEW RELEASE and might not reflect the final release.

http://www.mono-project.com/docs/about-mono/releases/4.4.0

**Comment by demmm** [comment]
There are a few things that can be done.
One, take the mono 4.2 PKGBUILD and files from KaOS [main] github (just go through the history of mono)
https://github.com/KaOSx/main/tree/master/mono
https://github.com/KaOSx/main/blob/5437a13eaba6bbd6f5c09703bcca6359aacde636/mono/PKGBUILD
And add to KCP as "mono4.2", make it conflict & provide mono.
Then make this app depend on mono4.2.

There is an option to use epoch in the repo and go back to 4.2, if more apps have issues with 4.4.

Find a patch for what emby-server needs from old mono, and patch repo mono with that.

So, no need at all to remove, there is always a way :)

**Comment by Adurol** [comment]
> I think this package should be removed temporarily from kcp until the incompatibility is resolved (with mono 4.4).

Sorry, as far as I know, there is no way to remove `emby-server` temporarily from KCP. I agree with demm that adding `mono4.2` to KCP would be the fastest solution.

Even if it is broken right now, I don't see a reason to remove `emby-server` immediately as it's still actively developed and will hopefully catch up with Mono 4.4 in the future.

**Comment by demmm** [comment]
No need to add any to KCP, as noted in IRC, one more package is known to be broken in KCP due to mono 4.4
Nothing in the repos needs mono as a run depend, so back to mono 4.2 it is.
Your next updates will bring back the fully working mono 4.2.2 version.

**Comment by demmm** [comment]
Mono 4.2 is now up in [main], closing this issue.
@Astate maybe you can keep track in emby-server for when it is ready for it for newer mono?

**Comment by Astate** [comment]
I look at this closely
