### ISSUE TITLE
One or more Files are Invalid

### ISSUE THREAD

**Issue by ghost** [KaOS-Community-Packages/emby-server#3]
Hello,

This is the translation in French from the error I have.
Here is translated log :
-> emby-server found
  -> emby-migrate-database found
  -> emby-server.conf found
  -> emby-server.service found
==> Checking sources files zwith sha256sums...
    emby-server-3.0.6300.tar.gz ... OK
    emby-server ... OK
    emby-migrate-database ... KO
    emby-server.conf ... OK
    emby-server.service ... OK
==> ERREUR : One or more files are invalid
exit status 1
That's all I have.
Thanks you for your answer !

**Comment by Astate** [comment]
je regarde cela aussitôt que possible

**Comment by Astate** [comment]
Its ok now
