### ISSUE TITLE
Error: fail in build

### ISSUE THREAD

**Issue by dagodax** [KaOS-Community-Packages/emby-server#4]
`==> Iniciando build()…
XBuild Engine Version 14.0
Mono, Version 4.6.2.0
Copyright (C) 2005-2013 Various Mono authors

Build started 14/1/2017 2:29:30 p. m..
__________________________________________________
Project "/tmp/emby-server/src/Emby-3.1.2/MediaBrowser.Mono.sln" (build target(s)):
        Target ValidateSolutionConfiguration:
                Building solution configuration "Release Mono|Any CPU".
        Target Build:
                Project "/tmp/emby-server/src/Emby-3.1.2/MediaBrowser.Model/MediaBrowser.Model.csproj" (default target(s)):
                        Target PrepareForBuild:
                                Configuration: Release Platform: AnyCPU
                                Created directory "/tmp/emby-server/src/build/"
                                Created directory "obj/Release/"
                        Target GetReferenceAssemblyPaths:
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Unable to find framework corresponding to the target framework moniker '.NETPortable,Version=v4.5,Profile=Profile7'. Framework assembly references will be resolved from the GAC, which might not be the intended behavior.                                                
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : PCL Reference Assemblies not installed.
                        Task "GetReferenceAssemblyPaths" execution -- FAILED
                        Done building target "GetReferenceAssemblyPaths" in project "/tmp/emby-server/src/Emby-3.1.2/MediaBrowser.Model/MediaBrowser.Model.csproj".-- FAILED                                                                                                                                                                  
                Done building project "/tmp/emby-server/src/Emby-3.1.2/MediaBrowser.Model/MediaBrowser.Model.csproj".-- FAILED
        Task "MSBuild" execution -- FAILED
        Done building target "Build" in project "/tmp/emby-server/src/Emby-3.1.2/MediaBrowser.Mono.sln".-- FAILED
Done building project "/tmp/emby-server/src/Emby-3.1.2/MediaBrowser.Mono.sln".-- FAILED

Build FAILED.

Warnings:

/tmp/emby-server/src/Emby-3.1.2/MediaBrowser.Mono.sln (build) ->
(Build target) ->                                                                                                                                                      
/tmp/emby-server/src/Emby-3.1.2/MediaBrowser.Model/MediaBrowser.Model.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (GetReferenceAssemblyPaths target) ->

        /usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Unable to find framework corresponding to the target framework moniker '.NETPortable,Version=v4.5,Profile=Profile7'. Framework assembly references will be resolved from the GAC, which might not be the intended behavior.

Errors:

/tmp/emby-server/src/Emby-3.1.2/MediaBrowser.Mono.sln (build) ->
(Build target) ->
/tmp/emby-server/src/Emby-3.1.2/MediaBrowser.Model/MediaBrowser.Model.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (GetReferenceAssemblyPaths target) ->

        /usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : PCL Reference Assemblies not installed.

         1 Warning(s)
         1 Error(s)

Time Elapsed 00:00:00.9753220
==> ERROR: Se produjo un fallo en build().
    Cancelando…
exit status 2
`

**Comment by Astate** [comment]
You need install PCL reference assembly

I Will check dep soon

**Comment by Astate** [comment]
Before install, you need to install this package from KCP:

kcp -di referenceassemblies-pcl

**Comment by dagodax** [comment]
Ok, it's working now.
